###
# @name Refund
#
POST https://sandbox.playtomic.io/v1/stripe-simulator/payments/256f6642-e866-453c-84b6-4d295428f32f/refunds

### Send POST request with json body
# @name Charge
#
POST https://sandbox.playtomic.io/v1/stripe-simulator/charges
Content-Type: application/json

{
  "credit_card": "1234567890",
  "amount": "123.456"
}

###
