camel:
  springboot:
    name: Wallet
    stream-caching-enabled: true
    stream-caching-statistics-enabled: true
  servlet:
    mapping:
      context-path: /*
server:
  port: 8090
spring:
  profiles:
    active: develop
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
stripe:
  simulator:
    charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
    refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
